FROM lscr.io/linuxserver/beets@sha256:9ddea6a905a1d322ab321bda0b60d5051ee05a7587860bf82a26b7469f276697
RUN apk add --no-cache git
RUN pip install --no-cache-dir git+https://github.com/edgars-supe/beets-importreplace.git
