FROM lscr.io/linuxserver/beets@sha256:ad08b158818c8f26ecb747edec045937a5913f2f087c53894c7511ba5d136199
RUN apk add --no-cache git
RUN pip install --no-cache-dir git+https://github.com/edgars-supe/beets-importreplace.git
