FROM lscr.io/linuxserver/beets@sha256:7c3c862e5b6a2ba11ffa172ef13cf91bb2b8755eb725b8fe969d25489e7c01b4
RUN apk add --no-cache git
RUN pip install --no-cache-dir git+https://github.com/edgars-supe/beets-importreplace.git
